In [ ]:
my_list = [1,2,3,4]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [ ]:
np.zeros(3) #vectors of zeros..

array([0., 0., 0.])

In [ ]:
np.zeros((5,5)) #rows of and colum

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,10) #genarate number of list from low to max of given argumented numbers of items

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(5) #for genarate the indentity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

More about np.eye at here --> https://numpy.org/devdocs/reference/generated/numpy.eye.html

### numpy.random.rand [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

In [ ]:
np.random.rand(5) ## Create array of given shape and populate it with random samples from a uniform distribution over [0, 1).

array([0.33091145, 0.07857156, 0.29326626, 0.9950705 , 0.33376359])

In [ ]:
np.random.rand(5,5)

### numpy.random.randn [more here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [ ]:
np.random.randn(2)

array([0.80135509, 0.62497373])

### numpy.random.randint [more here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)

In [ ]:
np.random.randint(1,100)

29

In [ ]:
np.random.randint(1,100,10)

array([22,  3, 70, 66, 20, 14, 86, 43, 45, 43])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([18, 15, 29,  8, 18, 49, 30,  0, 26,  0])

In [ ]:
arr.reshape(5,5) #-->reshape(rew,col) row*col == len(arr)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max() #for geting max of a list

49

In [ ]:
ranarr.min() #for getting min of a list

0

In [ ]:
ranarr.argmax() ## index of max value in the list

5

In [ ]:
ranarr.argmin() #index  of min value in a list

7

In [ ]:
arr.shape #to size of the list and dimention of list [return a tuple of size]

(25,)

In [ ]:
arr = arr.reshape(5,5) 

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int32')