In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr [:] =88
slice_of_arr


array([88, 88, 88, 88, 88, 88])

In [ ]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [ ]:
arr_cooy[:]=100
print(arr_cooy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[88 88 88 88 88 88  6  7  8  9 10]


 ### Matrix

In [ ]:
arr_2d = np.array([[5,6,7],[3,2,1],[8,9,10]])
arr_2d

array([[ 5,  6,  7],
       [ 3,  2,  1],
       [ 8,  9, 10]])

In [ ]:
print(arr_2d[2,1], arr_2d[2][1])

9 9


In [ ]:
print(arr_2d[:2])
print(arr_2d[:,1:])

[[5 6 7]
 [3 2 1]]
[[ 6  7]
 [ 2  1]
 [ 9 10]]


In [ ]:
arr_2d[:2, 1:]

array([[6, 7],
       [2, 1]])

In [ ]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

In [ ]:
arr_2d[1:3, ]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])